package edu.seu.vcampus.client.service.dorm;

import edu.seu.vcampus.client.network.NetworkClientException;
import edu.seu.vcampus.common.dto.dorm.AccessRecordDto;
import edu.seu.vcampus.common.dto.dorm.AccessRecordRequest;
import edu.seu.vcampus.common.dto.dorm.AccommodationDto;
import edu.seu.vcampus.common.dto.dorm.AccommodationRequest;
import edu.seu.vcampus.common.dto.dorm.AccommodationRequestDto;
import edu.seu.vcampus.common.dto.dorm.AnnouncementSaveRequest;
import edu.seu.vcampus.common.dto.dorm.DormAnnouncementDto;
import edu.seu.vcampus.common.dto.dorm.DormApprovalRequest;
import edu.seu.vcampus.common.dto.dorm.DormAssignmentRequest;
import edu.seu.vcampus.common.dto.dorm.DormBedDto;
import edu.seu.vcampus.common.dto.dorm.DormBedWriteRequest;
import edu.seu.vcampus.common.dto.dorm.DormBuildingDto;
import edu.seu.vcampus.common.dto.dorm.DormBuildingWriteRequest;
import edu.seu.vcampus.common.dto.dorm.DormPage;
import edu.seu.vcampus.common.dto.dorm.DormPageQuery;
import edu.seu.vcampus.common.dto.dorm.DormRoomDto;
import edu.seu.vcampus.common.dto.dorm.DormRoomWriteRequest;
import edu.seu.vcampus.common.dto.dorm.HygieneInspectionDto;
import edu.seu.vcampus.common.dto.dorm.HygieneInspectionRequest;
import edu.seu.vcampus.common.dto.dorm.LateReturnAlertDto;
import edu.seu.vcampus.common.dto.dorm.LateReturnHandleRequest;
import edu.seu.vcampus.common.dto.dorm.LeaveCancelRequest;
import edu.seu.vcampus.common.dto.dorm.LeaveQuery;
import edu.seu.vcampus.common.dto.dorm.LeaveRequestDto;
import edu.seu.vcampus.common.dto.dorm.LeaveReviewRequest;
import edu.seu.vcampus.common.dto.dorm.LeaveSubmitRequest;
import edu.seu.vcampus.common.dto.dorm.RepairCreateRequest;
import edu.seu.vcampus.common.dto.dorm.RepairEvaluationRequest;
import edu.seu.vcampus.common.dto.dorm.RepairOrderDto;
import edu.seu.vcampus.common.dto.dorm.RepairStatusRequest;
import edu.seu.vcampus.common.dto.dorm.UtilityBillDto;
import edu.seu.vcampus.common.dto.dorm.UtilityBillQuery;
import edu.seu.vcampus.common.dto.dorm.UtilityPaymentRequest;

/** 宿舍客户端网络边界，不暴露服务端仓储或数据库对象。 */
public interface DormClientService {
    DormPage<DormBuildingDto> buildings(DormPageQuery query) throws NetworkClientException;
    DormPage<DormRoomDto> rooms(DormPageQuery query) throws NetworkClientException;
    DormPage<DormBedDto> beds(DormPageQuery query) throws NetworkClientException;
    DormBuildingDto createBuilding(DormBuildingWriteRequest request) throws NetworkClientException;
    DormBuildingDto updateBuilding(DormBuildingWriteRequest request) throws NetworkClientException;
    DormRoomDto createRoom(DormRoomWriteRequest request) throws NetworkClientException;
    DormRoomDto updateRoom(DormRoomWriteRequest request) throws NetworkClientException;
    DormBedDto createBed(DormBedWriteRequest request) throws NetworkClientException;
    DormBedDto updateBed(DormBedWriteRequest request) throws NetworkClientException;
    AccommodationDto myAccommodation() throws NetworkClientException;
    AccommodationDto assign(DormAssignmentRequest request) throws NetworkClientException;
    AccommodationDto transfer(DormAssignmentRequest request) throws NetworkClientException;
    AccommodationDto checkout(DormAssignmentRequest request) throws NetworkClientException;
    AccommodationRequestDto submitRequest(AccommodationRequest request) throws NetworkClientException;
    DormPage<AccommodationRequestDto> requests(DormPageQuery query, Long studentUserId) throws NetworkClientException;
    AccommodationRequestDto approveRequest(DormApprovalRequest request) throws NetworkClientException;
    AccessRecordDto recordAccess(AccessRecordRequest request) throws NetworkClientException;
    DormPage<AccessRecordDto> access(DormPageQuery query, Long studentUserId) throws NetworkClientException;
    DormPage<LateReturnAlertDto> alerts(DormPageQuery query, Long studentUserId) throws NetworkClientException;
    LateReturnAlertDto handleAlert(LateReturnHandleRequest request) throws NetworkClientException;
    DormPage<HygieneInspectionDto> hygiene(DormPageQuery query) throws NetworkClientException;
    HygieneInspectionDto saveHygiene(HygieneInspectionRequest request) throws NetworkClientException;
    DormPage<RepairOrderDto> repairs(DormPageQuery query) throws NetworkClientException;
    RepairOrderDto createRepair(RepairCreateRequest request) throws NetworkClientException;
    RepairOrderDto updateRepair(RepairStatusRequest request) throws NetworkClientException;
    RepairOrderDto evaluateRepair(RepairEvaluationRequest request) throws NetworkClientException;
    LeaveRequestDto submitLeave(LeaveSubmitRequest request) throws NetworkClientException;
    DormPage<LeaveRequestDto> myLeaves(LeaveQuery query) throws NetworkClientException;
    LeaveRequestDto cancelLeave(LeaveCancelRequest request) throws NetworkClientException;
    DormPage<LeaveRequestDto> managerLeaves(LeaveQuery query) throws NetworkClientException;
    LeaveRequestDto reviewLeave(LeaveReviewRequest request) throws NetworkClientException;
    DormPage<UtilityBillDto> bills(DormPageQuery query) throws NetworkClientException;
    DormPage<UtilityBillDto> managerBills(UtilityBillQuery query) throws NetworkClientException;
    UtilityBillDto payBill(UtilityPaymentRequest request) throws NetworkClientException;
    DormPage<DormAnnouncementDto> announcements(DormPageQuery query) throws NetworkClientException;
    DormAnnouncementDto saveAnnouncement(AnnouncementSaveRequest request) throws NetworkClientException;
}
